### ISSUE TITLE
Please help me to revert if input is a string?

### ISSUE THREAD

**Issue by thinhbui** [pur3miish/base58-js#1]
I passed wrong input as string to binary_to_base58 but I dont save the string.

Ex: binary_to_base58('33,214,187,209,15,21,13,207,171,148,20,163,225,122,194') => '3QrLi8JLWSrXE91RAthGWLmQjuW7bKpJs22C35mSo2YfjPsc3HZF4TFNRPXbAD6gbRcd1751oR'

How can i get the string from base58? Please help me!!! I need to get back my private key

**Comment by pur3miish** [comment]
Try the following code below to see if you can replicate the results.

```js
const { base58_to_binary, binary_to_base58 } = require('base58-js')

const binary_arr = [
  33, 214, 187, 209, 15, 21, 13, 207, 171, 148, 20, 163, 225, 122, 194
]
const base58_str = binary_to_base58(binary_arr) // wuiVaZ1mY8thfQd5PzX3

const binary_str = base58_to_binary(base58_str)

console.log(binary_str) // Uint8Array [33, 214, 187, 209, 15, 21, 13, 207, 171, 148, 20, 163, 225, 122, 194]

```

**Comment by thinhbui** [comment]
@pur3miish I passed wrong type as string like "33, 214, 187, 209, 15, 21, 13, 207, 171, 148, 20, 163, 225, 122, 194" so I cant get back by base58_to_binary. 
Is there any way i can get it back?
